apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{coral.app}}
  namespace: bigbang
  labels:
    app.kubernetes.io/name: {{coral.app}}
    app.kubernetes.io/component: "service"
spec:
  interval: 1m
  url: https://github.com/csemissionplatformops/big-bang-istio-service.git
  ref:
    branch: main
    tag: {{chartTag}}
